### ISSUE TITLE
Front end version

### ISSUE THREAD

**Issue by Ewan-Roberts** [davidfig/pixi-intersects#4]
I know one should pack this up and serve to the front end with some magic, however i am unfortunately not gifted in this area. :( 

Do you have a front end version of this?

**Comment by davidfig** [comment]
I added umd/intersects.min.js to v.2.2.0. It should be picked up by the cdns. Hopefully that helps.

**Comment by davidfig** [comment]
What do you mean? Are you looking for a pixi-intersects.min.js file that is served by cdns?

**Comment by Fiyanov** [comment]
I can't find pixi-intersects.min.js  anywhere... and i can't understand what tool use for build it...  Can you write little instruction for that?

**Comment by davidfig** [comment]
You should look into bundling your code through one of the available bundlers. I use browserify (http://browserify.org/), but you can also use rollup (https://rollupjs.org/guide/en) or any number of bundlers. That way you can quickly and easily add modules from npmjs.com.

The way to bundle this library (and many libraries) is something like this:
```js
const Intersects = require('pixi-intersects')

Intersects.function...()
```
You then run the bundler and it compiles all your libraries into a single javascript file that you include in your index.html. 

Just a note, I have not worked on this particular library in about three years. I use my other library: https://www.npmjs.com/package/intersects for intersection tests. You may want to look at it. 

Good luck!
